version: "3.8"

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - mysql_data:/var/lib/mysql
      - ./message.sql:/docker-entrypoint-initdb.d/message.sql
    networks:
      - twotier
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  flaskapp:
    build: .
    container_name: flaskapp
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - twotier
    
volumes:
  mysql_data:
networks:
  twotier:
    driver: bridge